### ISSUE TITLE
Return indices that sort the array

### ISSUE THREAD

**Issue by certik** [swenson/sort#12]
It would be nice to also have a version of the sorter functions that return indices that sort the array (just like [argsort](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html) in NumPy).

This can then be used to sort multiple arrays at once (for example eigenvalues and the corresponding eigenvectors, etc.), which is extremely useful.

**Comment by swenson** [comment]
As this issue can be solved by redefining `SORT_SWAP` (albeit, not the most elegant solution), I think it would be tedious and potentially slow to add an `argsort`-like option to all of our sorting algorithms.

Closing for now.
