### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [swenson/sort#45]
I would like to point out that an identifier like “[`__SORT_SWAP_t`](https://github.com/swenson/sort/blob/fcb7647e37419e18e5410457060b05f3afcefaa3/sort.h#L27 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by swenson** [comment]
I fixed this identifier to conform. I didn't notice any other violations.

Thanks for pointing this out!
