### ISSUE TITLE
Is the tim sort implemented stable?

### ISSUE THREAD

**Issue by liwt31** [swenson/sort#47]
I noticed the following code in tim sort:

> https://github.com/swenson/sort/blob/d360ba02ca55803673ead2497d352135a9aa291e/sort.h#L737-L747

If the run in `dst` contains duplicate elements in the middle, they are pairwise swapped here, hence making tim sort unstable.

Now sure if I'm right or wrong - I'm new to tim sort and trying to learn from your code, so I apologize if I have made any mistakes.

**Comment by swenson** [comment]
Yes, tim sort is implemented stably.

`REVERSE_ELEMENTS` is only called in one place: when there is a strictly decreasing run of elements. https://github.com/swenson/sort/blob/d360ba02ca55803673ead2497d352135a9aa291e/sort.h#L796

Part of the stress testing is to check that it is stable as well (though of course, there could always be a bug).

Thanks for checking!

**Comment by liwt31** [comment]
I understand now. Thank you very much for the clarification!
