### ISSUE TITLE
Gallop mode in timsort

### ISSUE THREAD

**Issue by liwt31** [swenson/sort#49]
I haven't found the gallop mode code in timsort, which I believe is an important feature of it.
Is there a particular reason for it? For example, did some tests demonstrate timsort without gallop is better?
If not, do you accept PR related to that?
Thanks in advance.

**Comment by swenson** [comment]
I would accept a PR with it if it demonstrated performance increases.

When I read through the algorithm initially, it seemed the gallop mode could make performance worse in some circumstances. The extra complexity didn't seem worth the potential gain (which seemed to be limited to certain special cases).

**Comment by liwt31** [comment]
IMHO, on the one hand, the gallop mode is optimized for nearly sorted input. while on the other hand it's also designed to avoid large overhead when data distribution is random. As [Tim himself points out](
https://github.com/python/cpython/blob/ea9c8bd44365ae8b0accc5286c7b52862528c0ec/Objects/listsort.txt#L412-L418):
> These preliminary searches may not pay off, and can be expected *not* to
repay their cost if the data is random.  But they can win huge in all of
time, copying, and memory savings when they do pay, so this is one of the
"per-merge overheads" mentioned above that we're happy to endure because
there is at most one very short run.  It's generally true in this algorithm
that we're willing to gamble a little to win a lot, even though the net
expectation is negative for random data.

**Comment by swenson** [comment]
Ah, yes. I think I had chosen not to include galloping because of the comment at the end:

> the net expectation is negative for random data

However, I think it would still be good to do.

**Comment by nwellnhof** [comment]
I found some issues with the new gallop mode implementation. See my comments here: https://github.com/swenson/sort/pull/51/files. The `ofs << 1 + 1` issue could be serious but I don't have time to investigate further.

**Comment by liwt31** [comment]
@nwellnhof  Thanks for your comment! I'll look into this recently. `ofs << 1 + 1` is a silly mistake, but luckily IMHO it won't be a very serious issue. The difference between `ofs << 1 + 1` and `(ofs << 1) + 1` is that `ofs` will increase more quickly in the first case, which will decrease the performance of the algorithm a little bit, but no overflow will occur because boundary checks are necessary for `(ofs << 1) + 1` and thus are always performed.

**Comment by swenson** [comment]
I will look into addressing those comments soon!

**Comment by swenson** [comment]
I did some cleanup, and looked into the `ofs` issue here: https://github.com/swenson/sort/pull/56

The `ofs` issue is deeper. I'm going to have to give it a more thorough look before messing with the behavior of that code though. Expect another PR soon.

**Comment by swenson** [comment]
I think we got this sorted now. Thanks for the feedback everyone. Closing this for now. Feel free to open up another issue if you notice anything.
