### ISSUE TITLE
undefined reference to `__builtin_clzll'

### ISSUE THREAD

**Issue by noloader** [swenson/sort#58]
The head notes of GNU GetText show this. My apologies of this is not a swenson-sort issue.

```
/*
 * Taken from https://github.com/swenson/sort
 * Revision: 05fd77bfec049ce8b7c408c4d3dd2d51ee061a15
 * Removed all code unrelated to Timsort and made minor adjustments for
 * cross-platform compatibility.
 */
```

GNU GetText is failing to compile on 32-bit older systems. The error under GCC 3.3 is:

```
$ cat ~/get-text.txt
libtool: link: gcc -std=gnu99 -g2 -O2 -fPIC -pthread -Wl,-R -Wl,\$ORIGIN/../lib -Wl,-R -Wl,/usr/local/lib -Wl,--enable-new-dtags -o .libs/hello hello.o  -L/usr/local/lib ../lib/.libs/libtextstyle.so /usr/local/lib/libiconv.so -lm -ldl -lpthread -pthread -Wl,-rpath -Wl,/usr/local/lib
../lib/.libs/libtextstyle.so: undefined reference to `__builtin_clzll'
collect2: ld returned 1 exit status
make[4]: *** [hello] Error 1
make[4]: Leaving directory `/home/test/gettext-0.20.1/libtextstyle/adhoc-tests'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/test/gettext-0.20.1/libtextstyle'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/test/gettext-0.20.1/libtextstyle'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/test/gettext-0.20.1'
make: *** [all] Error 2
Failed to build GetText
```

And:

```
gettext-0.20.1$ grep -IR __builtin_clzll
libtextstyle/lib/libxml/timsort.h:#define CLZ __builtin_clzll
gettext-tools/gnulib-lib/libxml/timsort.h:#define CLZ __builtin_clzll
gnulib-local/lib/libxml/timsort.h:#define CLZ __builtin_clzll
```

And:

```
gettext-0.20.1$ cat libtextstyle/lib/libxml/timsort.h
...

#ifndef CLZ
#ifdef __GNUC__
#define CLZ __builtin_clzll
#else

static int clzll(uint64_t);

/* adapted from Hacker's Delight */
static int clzll(uint64_t x) {
  int n;

  if (x == 0) {
    return 64;
  }

  n = 0;

  if (x <= 0x00000000FFFFFFFFL) {
    n = n + 32;
    x = x << 32;
  }

  if (x <= 0x0000FFFFFFFFFFFFL) {
    n = n + 16;
    x = x << 16;
  }

  if (x <= 0x00FFFFFFFFFFFFFFL) {
    n = n + 8;
    x = x << 8;
  }

  if (x <= 0x0FFFFFFFFFFFFFFFL) {
    n = n + 4;
    x = x << 4;
  }

  if (x <= 0x3FFFFFFFFFFFFFFFL) {
    n = n + 2;
    x = x << 2;
  }

  if (x <= 0x7FFFFFFFFFFFFFFFL) {
    n = n + 1;
  }

  return n;
}

#define CLZ clzll
#endif
#endif
```

It may be a good idea to perform an actual feature test for availability of `__builtin_clzll`.

**Comment by swenson** [comment]
Thanks for the bug report. It looks like that function was added in GCC 3.4.0, released on April 18, 2004.

I will add a check for at least that version shortly.

**Comment by noloader** [comment]
@swenson,

If interested for testing... You can setup a [Ubuntu 4 machine](http://old-releases.ubuntu.com/releases/) and a [Fedora 1 machine](https://archive.fedoraproject.org/pub/archive/fedora/linux/core/) for testing.

I use them for compile and regression tests using ancient GCC and runtime libraries. I am particularly interested in older GCC to ensure we don't break things moving forward.

**Comment by swenson** [comment]
Good to know. I normally do my testing on Travis-CI for this repo, which I think doesn't support systems this old. :) Maybe I can setup something though.

I also realize that this conditional won't support clang very well, so I'll add a fix for that later today as well to increase clang performance.

**Comment by swenson** [comment]
It looks like this was fixed few months ago by @korli:

https://github.com/swenson/sort/commit/8aa6a0c961bc9a7389ec82b6e77cb48eb133e21f

So. nothing to do there except update `sort.h` with the latest version (or fix that line in your copy).

**Comment by noloader** [comment]
Thanks man!
