### ISSUE TITLE
merge_sort is unstable?

### ISSUE THREAD

**Issue by Baobaobear** [swenson/sort#65]
The readme says "Merge sort (stable)", but from my test result, it looks unstable

**Comment by Baobaobear** [comment]
Oh, I understanded, the BITONIC_SORT when len <= 16 is unstable

**Comment by swenson** [comment]
Oh, interesting. I didn't realize that was a consequence of adding Bitonic sorting.

I'll work on adding a documented flag to force use a slower, stable sort as `SMALL_SORT`.

**Comment by Baobaobear** [comment]
It’s stable now, close

**Comment by dzaima** [comment]
This is still not documented anywhere (as far as I can tell), and without knowing this, "Timsort (stable)" in the readme is just wrong.

**Comment by MusicTheorist** [comment]
@dzaima But Timsort _is_ a stable sort?

**Comment by dzaima** [comment]
> @dzaima But Timsort _is_ a stable sort?
By itself it is, but [for less than 64 items](https://github.com/swenson/sort/blob/f79f2a525d03f102034b5a197c395f046eb82708/sort.h#L1736-L1739) this implementation calls [bitonic sort](https://github.com/swenson/sort/blob/f79f2a525d03f102034b5a197c395f046eb82708/sort.h#L147), which isn't stable.

**Comment by swenson** [comment]
Ah, thanks for pointing this out. I'll make a few changes today so that stable sorts don't use bitonic at smaller sizes.

**Comment by swenson** [comment]
This should be fixed now with #81
